### ISSUE TITLE
[Community]: Current TODO

### ISSUE THREAD

**Issue by HardcodedCat** [HardcodedCat/termux-monet#74]
### Feature description

# TODO:

 - [ ] Add Horizontal Cursor Scrolling and Text Wrap Toggle
 - [ ] Fix Holding Keyboard button in sidebar Menu
 - [ ] Optional Property Extra Keys Auto-hiding in landscape
 - [ ] Line Height Optional Property
 - [ ] Monet Background Theme
 - [ ] Optional Blurred and Transparent Extra Keys
 - [ ] Use A12+'s Native blur when on A12+, and RealtimeBlurView only in older SDKs
 - [ ] Change package name in order to be accepted in IzzyOnDroid
 - [ ] Build modded bootstrap packages for termux-monet (or make the app compatible with official ones, even with different package name)

### Additional information

a

**Comment by PrimusAnon** [comment]
So sorry if this is not the correct place to ask this, but I am a super noob when it comes to termux but it seems like monet is the way I should go with (as I have android v12 with no foreseeable upgrade to v13) I can install regular termux, but I don't know how to install monet, could someone please help me? Or give me a brief walkthrough? I can't even find videos online, sorry once again if this is the wrong place for this kind of question or if it has already been answered, could someone link me to it? Thank you so much.
